#!/usr/bin/env python3
"""Compile the engine's HLSL shaders and embed the results in C++ headers.

SDL_GPU does not compile shaders at runtime; each graphics API wants its own
format. For every shader in engine/render/shaders/*.{vert,frag}.hlsl this
script produces:

  * SPIR-V bytecode for Vulkan (Windows and Linux), via glslangValidator
  * Metal Shading Language source for macOS, via spirv-cross

and writes both into engine/render/shaders/compiled/<name>.h as arrays.
The generated headers are committed, so building the engine needs neither
tool; run this script only after editing a shader.

Tools: glslangValidator and spirv-cross, from the Vulkan SDK on Windows and
macOS, or `apt install glslang-tools spirv-cross` on Ubuntu.

The plan's long-term route is SDL_shadercross, which also emits DXIL for
Direct3D 12. Until then Windows runs SDL_GPU's Vulkan backend.
"""

import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHADER_DIR = ROOT / "engine" / "render" / "shaders"
OUT_DIR = SHADER_DIR / "compiled"


def run(cmd):
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"command failed: {' '.join(map(str, cmd))}\n{result.stdout}{result.stderr}")
    return result.stdout


def c_identifier(path):
    # mesh.vert.hlsl -> mesh_vert
    return path.name.removesuffix(".hlsl").replace(".", "_")


def byte_array(data, indent="    "):
    lines = []
    for i in range(0, len(data), 16):
        lines.append(indent + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    return "\n".join(lines)


def compile_one(src, tmp):
    stage = "vert" if ".vert." in src.name else "frag"
    spv = tmp / (src.stem + ".spv")
    # -V: produce SPIR-V for Vulkan, -D: the input is HLSL.
    run(["glslangValidator", "-V", "-D", "-e", "main", "-S", stage, str(src), "-o", str(spv)])
    msl = run(["spirv-cross", str(spv), "--msl", "--msl-version", "20100"])
    return spv.read_bytes(), msl


def main():
    OUT_DIR.mkdir(exist_ok=True)
    sources = sorted(SHADER_DIR.glob("*.hlsl"))
    # Group vert/frag pairs by shader name: mesh.vert.hlsl + mesh.frag.hlsl -> mesh.h
    groups = {}
    for src in sources:
        groups.setdefault(src.name.split(".")[0], []).append(src)

    with tempfile.TemporaryDirectory() as tmp_name:
        tmp = pathlib.Path(tmp_name)
        for name, files in groups.items():
            parts = [
                "// GENERATED by tools/compile_shaders.py from " + ", ".join(f.name for f in files) + ".",
                "// Do not edit; change the .hlsl files and re-run the script.",
                "#pragma once",
                "",
                "#include <cstddef>",
                "",
                "namespace eng::shaders {",
                "",
            ]
            for src in files:
                ident = c_identifier(src)
                spv, msl = compile_one(src, tmp)
                parts += [
                    f"// SPIR-V for Vulkan. Entry point: \"main\".",
                    f"inline constexpr unsigned char {ident}_spv[] = {{",
                    byte_array(spv),
                    "};",
                    "",
                    f"// Metal Shading Language source for macOS. Entry point: \"main0\".",
                    f"inline constexpr char {ident}_msl[] = R\"msl({msl})msl\";",
                    "",
                ]
            parts += ["} // namespace eng::shaders", ""]
            out = OUT_DIR / f"{name}.h"
            out.write_text("\n".join(parts))
            print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
